/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './resources/**/*.blade.php',
        './resources/**/*.js',
    ],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                'surface': '#fcf9f8',
                'surface-dim': '#dcd9d9',
                'surface-bright': '#fcf9f8',
                'surface-container-lowest': '#ffffff',
                'surface-container-low': '#f6f3f2',
                'surface-container': '#f0eded',
                'surface-container-high': '#eae7e7',
                'surface-container-highest': '#e4e2e1',
                'on-surface': '#1b1c1c',
                'on-surface-variant': '#43474f',
                'inverse-surface': '#303030',
                'inverse-on-surface': '#f3f0f0',
                'outline': '#737780',
                'outline-variant': '#c3c6d1',
                'surface-tint': '#3a5f94',
                'primary': '#001e40',
                'on-primary': '#ffffff',
                'primary-container': '#003366',
                'on-primary-container': '#799dd6',
                'inverse-primary': '#a7c8ff',
                'secondary': '#735c00',
                'on-secondary': '#ffffff',
                'secondary-container': '#fed65b',
                'on-secondary-container': '#745c00',
                'tertiary': '#1c1f20',
                'on-tertiary': '#ffffff',
                'tertiary-container': '#313435',
                'on-tertiary-container': '#9a9c9d',
                'error': '#ba1a1a',
                'on-error': '#ffffff',
                'error-container': '#ffdad6',
                'on-error-container': '#93000a',
                'primary-fixed': '#d5e3ff',
                'primary-fixed-dim': '#a7c8ff',
                'on-primary-fixed': '#001b3c',
                'on-primary-fixed-variant': '#1f477b',
                'secondary-fixed': '#ffe088',
                'secondary-fixed-dim': '#e9c349',
                'on-secondary-fixed': '#241a00',
                'on-secondary-fixed-variant': '#574500',
                'tertiary-fixed': '#e1e3e4',
                'tertiary-fixed-dim': '#c5c7c8',
                'on-tertiary-fixed': '#191c1d',
                'on-tertiary-fixed-variant': '#454748',
                'background': '#fcf9f8',
                'on-background': '#1b1c1c',
                'surface-variant': '#e4e2e1',
            },
            fontFamily: {
                'display-lg': ['"Playfair Display"', 'serif'],
                'headline-lg': ['"Playfair Display"', 'serif'],
                'headline-md': ['"Playfair Display"', 'serif'],
                'body-lg': ['Inter', 'sans-serif'],
                'body-md': ['Inter', 'sans-serif'],
                'label-md': ['Inter', 'sans-serif'],
                'caption': ['Inter', 'sans-serif'],
            },
            fontSize: {
                'display-lg': ['56px', { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '700' }],
                'display-lg-mobile': ['40px', { lineHeight: '48px', fontWeight: '700' }],
                'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
                'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
                'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
                'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
                'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
                'caption': ['12px', { lineHeight: '16px', fontWeight: '400' }],
            },
            borderRadius: {
                DEFAULT: '0.25rem',
                lg: '0.5rem',
                xl: '0.75rem',
                full: '9999px',
            },
            spacing: {
                'base-unit': '8px',
                'gutter': '24px',
                'margin-mobile': '16px',
                'margin-desktop': '48px',
                'section-padding-lg': '80px',
            },
            maxWidth: {
                'container': '1280px',
            },
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
    ],
}